name: CI
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: echo-deploy
        run: echo "deploying azure infraestructure"
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
        
      - name: Set up Azure credentials
        run: echo '${{ secrets.AZURE_CREDENTIALS }}' > azure-credentials.json
        
      - name: Connection string
        run:  export CONN_STRING=az storage account show-connection-string --name saport --resource-group POCSignature-SEM-DEV --query connectionString --output tsv

      - name: Download tfstate
        run: az storage blob download --connection-string $CONN_STRING --container-name tfstate --name terraform.tfstate --file /
        
      - name: Destroy resources
        run: |
          terraform destroy -state=/

