name: CI

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Export variables
        run: |
          export ARM_SUBSCRIPTION_ID="7667bfd6-4676-4837-8d8c-f6f1bf9bc870"
          export ARM_TENANT_ID="ba351225-3ca4-45f4-b7cc-ff5556c74a3e"
          export ARM_CLIENT_ID="aa586f5a-a9b9-43cc-9255-9728dfccad47"
          export ARM_CLIENT_SECRET="AT98Q~TtiLmv3SUGyR7bAEyL0AYQbBZGNixgucb~"
      
      - name: Terraform init
        run: |
          terraform init -upgrade

      - name: Terraform validate
        run: |
          terraform validate

      - name: Terraform import Resource Group
        run: |
          terraform import azurerm_resource_group.example /subscriptions/7667bfd6-4676-4837-8d8c-f6f1bf9bc870/resourceGroups/POCSignature-SEM-DEV

      - name: Terraform plan
        run: |
          terraform plan

      - name: Terraform apply
        run: |
          terraform apply -input=false -auto-approve
