name: CI

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Export variables
        run: |
          export ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}
          export ARM_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}
          export ARM_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}
          export ARM_CLIENT_SECRET=${{ secrets.AZURE_CLIENT_SECRET }}
          export ARM_ACCESS_KEY=${{ secrets.AZURE_AS_KEY_ACCESS }}
      
      - name: Terraform init
        run: |
          terraform init -upgrade

      - name: Terraform validate
        run: |
          terraform validate

      - name: Terraform import Resource Group
        run: |
          terraform import azurerm_resource_group.example /subscriptions/7667bfd6-4676-4837-8d8c-f6f1bf9bc870/resourceGroups/POCSignature-SEM-DEV

      - name: Terraform plan
        run: |
          terraform plan

      - name: Terraform apply
        run: |
          terraform apply -input=false -auto-approve
