name: CI

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform init
        uses: hashicorp/terraform-github-actions@v0.6.3
        with:
          command: init
          tf_version: 0.14.9
          working_dir: .

      - name: Terraform validate
        uses: hashicorp/terraform-github-actions@v0.6.3
        with:
          tf_version: 0.14.9
          command: validate
          working_dir: .

      - name: Terraform import Resource Group
        run: |
          terraform import azurerm_resource_group.example /subscriptions/7667bfd6-4676-4837-8d8c-f6f1bf9bc870/resourceGroups/POCSignature-SEM-DEV

      - name: Terraform plan
        uses: hashicorp/terraform-github-actions@v0.6.3
        with:
          tf_version: 0.14.9
          command: plan
          working_dir: .

      - name: Terraform apply
        uses: hashicorp/terraform-github-actions@v0.6.3
        with:
          tf_version: 0.14.9
          command: apply
          working_dir: .
        env:
          TF_CLI_ARGS: "-input=false -auto-approve"
